### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/usr/share/atom'

### ISSUE THREAD

**Issue by vrcod** [atom/about#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Ubuntu 15.04
**Thrown From**: [about](https://github.com/atom/about) package, v1.3.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/usr/share/atom'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/usr/share/atom'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at tryFile (module.js:105:22)
    at tryExtensions (module.js:115:20)
    at tryPackage (module.js:93:31)
    at Function.Module._findPath (module.js:151:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/about/lib/about-view.js:6:16)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/about/lib/about-view.js:165:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at createAboutView (/usr/share/atom/resources/app.asar/node_modules/about/lib/about.js:16:19)
    at /usr/share/atom/resources/app.asar/node_modules/about/lib/about.js:35:18
    at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:460:22)
    at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:399:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/usr/share/atom/resources/app.asar/src/atom-environment.js:1039:19)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "racer"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @vrcod, what were you doing when this error occured?  Did you by any chance move the location of the Atom application when it was running?

**Comment by vrcod** [comment]
It seems to work fine again after the recent update.
